# Generated by Django 3.2.6 on 2021-08-25 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shareRes', '0002_auto_20210825_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='shareRes.category'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='keyword',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
